name: Blue-Green Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: <your-registry-name>.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: <your-registry-name>.azurecr.io/<your-image-name>:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Azure Container App
        uses: azure/container-apps@v1
        with:
          app-name: <your-app-name>
          sku: Standard
          os-type: Linux
          location: eastus
          resource-group: <your-resource-group>
          container-image-name: <your-registry-name>.azurecr.io/<your-image-name>:latest
          container-port: 80
          container-environment-variables: |
            KEY1=VALUE1
            KEY2=VALUE2
      - name: Create Blue and Green Revisions
        uses: azure/container-apps@v1
        with:
          app-name: <your-app-name>
          resource-group: <your-resource-group>
          revision-names: blue,green
      - name: Tag Blue Revision as Production
        uses: azure/container-apps@v1
        with:
          app-name: <your-app-name>
          resource-group: <your-resource-group>
          revision-name: blue
          revision-label: production
      - name: Route Traffic to Blue Revision
        uses: azure/container-apps@v1
        with:
          app-name: <your-app-name>
          resource-group: <your-resource-group>
          traffic: blue=100
      - name: Deploy to Blue Revision
        uses: azure/container-apps@v1
        with:
          app-name: <your-app-name>
          resource-group: <your-resource-group>
          revision-name: blue
          container-image-name: <your-registry-name>.azurecr.io/<your-image-name>:latest
      - name: Test Green Revision
        uses: azure/container-apps@v1
        with:
          app-name: <your-app-name>
          resource-group: <your-resource-group>
          revision-name: green
          container-image-name: <your-registry-name>.azurecr.io/<your-image-name>:latest
      - name: Interchange Blue and Green Revisions
        if: ${{ job.status == 'success' }}
        uses: azure/container-apps@v1
        with:
          app-name: <your-app-name>
          resource-group: <your-resource-group>
          traffic: blue=0,green=100
          revision-labels: blue=green,green=blue
